import random
from pathlib import Path

import numpy as np
import torch
import torchaudio
from scipy.io import wavfile
from scipy.signal import resample
from torch.utils.data import DataLoader, Dataset

from lib.funet.src.config import Config

# Snippets generated by tune-ssnet/generate_training_snippets.sh are 4kHz mono wav.
SAMPLE_RATE = 4000
SOURCE_NAMES = ["heart", "lung", "noise"]
VAL_FRACTION = 0.1  # fraction of snippets (by index, held out at the end) used for validation

class FetalPairs(Dataset):
    """Paired snippet dataset in the tune-ssnet .../training/.../fetal layout:
    {i}_mix.wav (mono or multi-channel) plus mono {i}_heart.wav, {i}_lung.wav,
    and optionally {i}_noise.wav.

    mix    -> (mix_channels, freq, frames)
    target -> (num_sources, freq, frames): [heart, lung] or [heart, lung, noise]

    mix and all sources are cropped in the time domain with a single shared
    offset so they stay time-aligned, and to a fixed length so the spectrogram
    frame count (and the default collate) is consistent across the batch. If a
    clip is shorter than crop_samples it is zero-padded. Cropped waveforms are
    then converted to power spectrograms.
    """

    def __init__(self, snippet_dir: str, indices: list, crop_samples: int, random_crop: bool,
                 n_fft: int, hop_length: int, divisor: int = 1):
        self.dir = Path(snippet_dir)
        self.indices = indices
        self.crop_samples = crop_samples
        self.random_crop = random_crop
        self.hop_length = hop_length
        self.divisor = divisor  # FUNet needs freq/time both divisible by 2**depth; see make_dataloaders
        self.spectrogram = torchaudio.transforms.Spectrogram(n_fft=n_fft, hop_length=hop_length)

    def __len__(self):
        return len(self.indices)

    def _load(self, name: str) -> torch.Tensor:
        # scipy instead of torchaudio.load: avoids the torchcodec backend dependency.
        _, data = wavfile.read(str(self.dir / name))
        if np.issubdtype(data.dtype, np.integer):  # normalize int PCM to [-1, 1]
            data = data.astype(np.float32) / np.iinfo(data.dtype).max
        else:
            data = data.astype(np.float32)
        if data.ndim == 1:
            return torch.from_numpy(data).reshape(1, -1)          # mono -> (1, T)
        return torch.from_numpy(np.ascontiguousarray(data.T))     # (T, C) wav -> (C, T)

    @staticmethod
    def _pad(x: torch.Tensor, n: int) -> torch.Tensor:
        if x.shape[-1] >= n:
            return x
        pad = torch.zeros(x.shape[0], n - x.shape[-1], dtype=x.dtype)
        return torch.cat([x, pad], dim=-1)

    def __getitem__(self, i: int):
        idx = self.indices[i]
        mix = self._load(f"{idx}_mix.wav")
        heart = self._load(f"{idx}_heart.wav")


        # Align lengths (snippets may differ by a sample), then crop/pad to a fixed size.
        n = self.crop_samples
        avail = min([mix.shape[-1], heart.shape[-1]])
        if avail >= n:
            start = random.randint(0, avail - n) if self.random_crop else 0
            sl = slice(start, start + n)
            mix = mix[:, sl]
            heart = heart[:, sl]
        else:
            mix = self._pad(mix, n)
            heart = self._pad(heart, n)

        # Power spectrogram magnitudes span orders of magnitude (raw audio, unnormalized);
        # log1p compresses that to a learnable range before it hits the first conv.
        spectrogram = torch.log1p(self.spectrogram(mix))

        # Crop freq/time down to a multiple of `divisor` so FUNet's pool/transpose-conv
        # levels exactly invert each other (see the ValueError raised in FUNet.forward).
        freq, time = spectrogram.shape[-2], spectrogram.shape[-1]
        freq -= freq % self.divisor
        time -= time % self.divisor
        spectrogram = spectrogram[:, :freq, :time]

        # heart is (1, time); drop the channel dim to match FUNet's (batch, time) output,
        # clip resample ringing below 0, and normalize into a proper distribution (sums to
        # 1) so it's a valid KLDivLoss target for the model's log-softmax output.
        heart_target = np.clip(resample(heart, num=spectrogram.shape[-1], axis=-1)[0], 0, None)
        heart_target = heart_target / (heart_target.sum() + 1e-12)

        return spectrogram, torch.from_numpy(heart_target).float()

def make_dataloaders(config: Config) -> tuple[DataLoader, DataLoader]:
    snippet_dir = config.data.train_dir
    crop_samples = config.train.crop_len * SAMPLE_RATE

    mix_files = sorted(Path(snippet_dir).glob("*_mix.wav"),
                        key=lambda p: int(p.stem.split("_")[0]))
    indices = [int(p.stem.split("_")[0]) for p in mix_files]
    if not indices:
        raise FileNotFoundError(f"No *_mix.wav snippets found in {Path(snippet_dir).absolute()}")

    n_val = max(1, int(len(indices) * VAL_FRACTION))
    train_idx, val_idx = indices[:-n_val], indices[-n_val:]
    if not train_idx:
        raise ValueError(f"Only {len(indices)} snippet(s); not enough to hold out a validation set.")

    divisor = 2 ** len(config.model.dilations)
    train_ds = FetalPairs(snippet_dir, train_idx, crop_samples, random_crop=True,
                           n_fft=config.data.n_fft, hop_length=config.data.hop_length, divisor=divisor)
    val_ds = FetalPairs(snippet_dir, val_idx, crop_samples, random_crop=False,
                         n_fft=config.data.n_fft, hop_length=config.data.hop_length, divisor=divisor)

    print(f"Loaded {len(indices)} snippets from {snippet_dir} -> {len(train_idx)} train / {len(val_idx)} val")

    train_dl = DataLoader(train_ds, batch_size=config.train.batch_size, shuffle=True,
                           num_workers=config.data.num_workers, pin_memory=True)
    val_dl = DataLoader(val_ds, batch_size=config.train.batch_size, shuffle=False,
                         num_workers=config.data.num_workers, pin_memory=True)
    return train_dl, val_dl
